name: API CI
#on: [push] // si no es un mono repo
on:
  push:
    branches:
      - '**'
    paths:
        -"./api/**"
        -".github/workflows/main.yml"

defaults:
  run:
  working-directory: ./api

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./api/package-lock.json
      - name: install
        shell: bash
        run: npm ci
      - name: run unit test
        shell: bash
        run: npm test
